import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Guess Idol",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi">
      <body>
        <main className="flex justify-center bg-[url('/bg_mobile.png')] bg-no-repeat bg-fixed min-w-screen bg-black inset-x-0 top-0 min-h-screen bg-top">
          {children}
        </main>
      </body>
    </html>
  );
}
